model: pydgn.model.dgn.ecgmm.ECGMM
experiment: pydgn.experiment.cgmm_embedding_task.EmbeddingCGMMTask
higher_results_are_better: True
dataset_getter: pydgn.data.provider.IncrementalDataProvider
log_every: 1
num_dataloader_workers: 2  # > 0 only with GPU device
pin_memory: True  # True only with GPU device
device: cuda 
grid:
  layer_config:
    embeddings_folder: [path where to save embeddings]
    checkpoint: True
    batch_size:
      - 16
    shuffle:
      - False
    previous_layers_to_use:
      - "1"  # multiple layers: "1,2,4"
    concatenate_on_axis: 1  # must be > 0
    max_layers:
      - 20
    C:
      - 20
    CA:
    - 5
    - 10
    #predictor: null
    node_predictor:
      - pydgn.model.predictor.node_predictor.UnsupervisedProbabilisticNodeReadout
    node_emission:
      - pydgn.model.distribution.emission.IsotropicGaussian
    edge_predictor:
      - pydgn.model.predictor.node_predictor.UnsupervisedProbabilisticNodeReadout
    edge_emission:
      - pydgn.model.distribution.emission.Categorical
    # LEAVE UNIBIGRAM TRUE: unigrams will be automatically generated by EmbeddingCGMMTask
    unibigram:
       - True
    aggregation:
      - mean
      - sum
    infer_with_posterior:
      - True
      - False
    epochs:
      - 10
    wrapper:
      - pydgn.training.engine.IncrementalTrainingEngine
    loss:
      - pydgn.training.callback.loss.CGMMLoss
    optimizer:
      - pydgn.training.callback.optimizer.CGMMOptimizer
    scorer:
      -
        class_name: pydgn.training.callback.score.MultiScore
        args:
           # used at model selection time. Should be the one on which to perform early stopping
           main_scorer: pydgn.training.callback.score.CGMMCompleteLikelihoodScore
           true_likelihood: pydgn.training.callback.score.CGMMTrueLikelihoodScore
    plotter:
      - pydgn.training.callback.plotter.Plotter
