splitter:
  root: DATA_SPLITS/
  class_name: pydgn.data.splitter.LinkPredictionSingleGraphSplitter
  args:
    n_outer_folds: 1
    n_inner_folds: 1
    seed: 42
    stratify: False
    shuffle: True
    val_ratio: 0.1
    test_ratio: 0.1
    undirected: True  # we need to know if the graph is undirected or not to create proper random splits
    avoid_opposite_negative_edges: True  # Useful for losses/scores that consider the direction. Has an effect when the graph is directed.
    run_checks: True  # in case you want to debug the first time. Computes full adj matrix, be careful.
dataset:
  root: DATA/
  class_name: pydgn.data.dataset.LinkPredictionKarateClub
  args:
    root: DATA/
    name: karateclub
