splitter:
  root: DATA_SPLITS/
  class_name: pydgn.data.splitter.LinkPredictionSingleGraphSplitter
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: False
    shuffle: True
    inner_val_ratio: 0.05
    outer_val_ratio: 0.05
    test_ratio: 0.1
    undirected: True  # we need to know if the graph is undirected or not to create proper random splits
    avoid_opposite_negative_edges: True  # Useful for losses/scores that consider the direction. Has an effect when the graph is directed.
    run_checks: True  # in case you want to debug the first time. Computes full adj matrix, be careful.
dataset:
  root: DATA/
  class_name: pydgn.data.dataset.LinkPredictionPlanetoid
  args:
    root: DATA/
    name: pubmed
  transform:
    - class_name: pydgn.data.transform.NormalizeFeatures
